### ISSUE TITLE
Creating Docker Container for AWS Batch

### ISSUE THREAD

**Issue by nordic96** [nordic96/Infinite_Challenge#23]

**Comment by nordic96** [comment]
Docker File Auto build will not work if Dockerfile is not located under `.Dockerfile/`

**Comment by briyanii** [comment]
Once we decide on the best way to handle credentials etc, I think I just need to build this image for it to work. see #44

Credentials required for AWS services can be passed to the container running in an AWS computing environment by attaching an IAM role with the permissions to access the services (at the moment, just S3) I think to access the RDS we need to do something regarding security groups?

As for non AWS services, we need figure out how to attach the credentials securely.

AWS batch does not seem to support t2.micro? I cannot find it in the instance types when trying to create a compute environment using the wizard, so using free tier hours may not be possible.

**Comment by nordic96** [comment]
> Once we decide on the best way to handle credentials etc, I think I just need to build this image for it to work. see #44
> 
> Credentials required for AWS services can be passed to the container running in an AWS computing environment by attaching an IAM role with the permissions to access the services (at the moment, just S3) I think to access the RDS we need to do something regarding security groups?
> 
> As for non AWS services, we need figure out how to attach the credentials securely.
> 
> AWS batch does not seem to support t2.micro? I cannot find it in the instance types when trying to create a compute environment using the wizard, so using free tier hours may not be possible.

I think for now, we can try using EC2 instead (VM) instead of Batch, the performance should increase significantly since we replaced both models with cloud services. But, I am not able to manage IAM roles in my AWS educate account. We can discuss after testing 1 full episode in our local (& docker) first. Thanks for the hardwork :)
