### ISSUE TITLE
Connecting the pipelines

### ISSUE THREAD

**Issue by nordic96** [nordic96/Infinite_Challenge#8]
Phase1 and Phase 2 needs to be connected
in Phase 1:
* video processing using skull detection
* save screenshot if skull is detected & create a csv with skull info (skull location(s), timestamp)

in Phase 2:
* facial recognition from saved screenshots
* update the created csv file from Phase 1 (member who is detected)

Finalised csv file should be ready #12 for db creation

**Comment by briyanii** [comment]
file structure of input and output files changed from that given in issue, see #15
